DDPB-3705: Make date of birth and address fields mandatory
ministryofjustice/serve-opg pull request #394
Opened 2020-11-03 13:08 UTC by coderste

## Description
As a OPG user
I want the COP users to enter the deputy DOB 
So that the deputy can be matched when the order is served and duplicates are not created in Sirius

I want the COP users to enter the deputy address
So that the deputy can be matched when the order is served and duplicates are not created in Sirius

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Merge check List

- [X] New functionality includes testing
- [ ] New functionality has been documented in the README if applicable **N/A**
- [ ] Approved by PMs

2020-11-04 11:20 UTC, coderste commented on src/Form/DeputyForm.php
> -                'hint' => 'deputy.emailAddress.hint',
Yeah from what I understand Symfony doesn't even have a `hint` option for forms. It was causing UnitTests to fail as it was saying `hint` doesn't exist

2020-11-04 11:48 UTC, Gugandeep commented on src/Form/DeputyForm.php
> -                'hint' => 'deputy.emailAddress.hint',
Looking into it you're right, I can't seem ti find a `hint `option.

Did find [this](https://symfony.com/blog/new-in-symfony-4-1-form-field-help) for a `help` option that's included in Symfony 4.1 should we want to use it in the future.

2020-11-04 11:49 UTC, Gugandeep submitted a review, later dismissed
Looks good to me!

2020-11-04 15:35 UTC, acsauk requested changes
Good job - just the translations to add for the validation messages and then good to go 👍

2020-11-04 15:35 UTC, acsauk commented on src/Entity/Deputy.php
> +     * @Assert\NotBlank(message="deputy.dateOfBirth.notBlank")
For all of these where we refer to `message="<SOMETHING>"` you'll need to add the corresponding translation to `/translations/validators.en.yml`.

2020-11-04 15:35 UTC, acsauk commented on src/Form/DeputyForm.php
> -                'hint' => 'deputy.emailAddress.hint',
You can remove the corresponding translation now as well.

2020-11-05 10:15 UTC, acsauk approved these changes
:shipit:

2020-11-11 10:54 UTC, merged