SER-186 - resolve Actions deprecation warnings
ministryofjustice/serve-opg pull request #535
Opened 2022-11-13 14:21 UTC by xaithe

## Description

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Issues Resolved

SER-XXX [List any existing issues this PR resolves]

## Merge check List

- [ ] New functionality includes testing
- [ ] New functionality has been documented in the README if applicable
- [ ] Approved by PMs

2022-12-16 17:53 UTC, mattmachell requested changes

2022-12-16 17:53 UTC, mattmachell commented on .github/workflows/api.yml
> +      - uses: actions/setup-python@v4
Do we need python here at all as it's just a go workflow?

2022-12-16 17:53 UTC, mattmachell commented on .github/workflows/behat.yml
>        - name: Set up Python 3.8.1
Worth updating the name here from 3.8.1

2022-12-16 17:53 UTC, mattmachell commented on .github/workflows/behat.yml
>            python-version: "3.x"
Might be worth pinning to a more specific version to avoid issues.

2022-12-16 17:53 UTC, mattmachell commented on .github/workflows/web.yml
> +        - name: Set up Python 3.10.9
Not sure we need python here at all since everything in the build step is dockerised.

2022-12-19 09:06 UTC, charlesmmarshall submitted a review, later dismissed

2022-12-20 14:53 UTC, charlesmmarshall approved these changes

2022-12-20 15:08 UTC, merged